### ISSUE TITLE
New-NanoServerVHD.ps1 does not work in windows 10

### ISSUE THREAD

**Issue by prabirshrestha** [PlagueHO/Powershell#9]

**Comment by PlagueHO** [comment]
Hi There,

You're right. The problem is in the Convert-WindowsImage.ps1 script. It mis-detects the OS as being lower than Windows 8. The creator of Convert-WindowsImage.ps1 has been notified of this:
https://gallery.technet.microsoft.com/scriptcenter/Convert-WindowsImageps1-0fe23a8f/view/Discussions#content

I have proposed a fix to this problem and will wait for the Convert-WindowsImage.ps1 script to get updated.

If you want to get it working now, edit the Convert-WindowsImage.ps1 script and locate the line:
$isWin8 = (($os.Version -ge 6.2) -and ($os.BuildNumber -ge $lowestSupportedBuild))

Replace it with:

$isWin8 = (([float]($os.Version.Split('.')[0]+'.'+$os.Version.Split('.')[1]) -ge 6.2) -and ([int]$os.BuildNumber -ge [int]$lowestSupportedBuild))

Thanks for your feedback!

**Comment by prabirshrestha** [comment]
commented it and set it to `$true`  and works :) Thanks.

```powershell
#$isWin8 = (($os.Version -ge 6.2) -and ($os.BuildNumber -ge $lowestSupportedBuild))
$isWin8 = $true
```

**Comment by PlagueHO** [comment]
Yep - that'll fix it too :)

**Comment by prabirshrestha** [comment]
closing this since it isn't actually the bug in `New-NanoServerVHD.ps1` script. Might be could rather mention it in the README.md for windows 10 users.
